-- Private schema: only the Express backend connects to these tables.
-- Legacy card duplicates and unresolved references are preserved intentionally.
CREATE SCHEMA kesari;
REVOKE ALL ON SCHEMA kesari FROM PUBLIC, anon, authenticated;

CREATE TABLE kesari.metadata (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE kesari.customers (
  "_order" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  id TEXT PRIMARY KEY, name TEXT NOT NULL, phone TEXT NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '', "cardNo" TEXT NOT NULL, "sourceRow" INTEGER,
  "createdAt" TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);
CREATE TABLE kesari.payments (
  "_order" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  id TEXT PRIMARY KEY, "cardNo" TEXT NOT NULL, "amountCents" BIGINT,
  date DATE, "fromDate" DATE, "untilDate" DATE,
  mode TEXT NOT NULL DEFAULT '', comment TEXT NOT NULL DEFAULT '', "sourceRow" INTEGER,
  "createdAt" TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);
CREATE TABLE kesari.recharges (
  "_order" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  id TEXT PRIMARY KEY, "cardNo" TEXT NOT NULL, date DATE, "fromDate" DATE, "untilDate" DATE,
  "sourceRow" INTEGER,
  "createdAt" TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);
CREATE INDEX customers_card ON kesari.customers("cardNo");
CREATE INDEX payments_card ON kesari.payments("cardNo");
CREATE INDEX recharges_card ON kesari.recharges("cardNo");
CREATE INDEX payments_date ON kesari.payments(date);
CREATE INDEX recharges_date ON kesari.recharges(date);
ALTER TABLE kesari.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE kesari.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE kesari.recharges ENABLE ROW LEVEL SECURITY;
ALTER TABLE kesari.metadata ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ALL TABLES IN SCHEMA kesari FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA kesari FROM PUBLIC, anon, authenticated;
